### ISSUE TITLE
little inconsistency in ex11

### ISSUE THREAD

**Issue by Andrea-V** [andreamad8/Algo2Problems#10]
In the first paragraph  m = 1/f' . Some lines below m = ceil(1/f) (NB: the first time is f prime and the second is only f). Which is the correct one?

**Comment by andreamad8** [comment]
The first paragraph of the exercise answer to the question:
The resulting space-efficient perfect hash table T has now a one-side error with failure probability of roughly f, as in Bloom filters: say why. 
Qui a detta di grossi dovevamo trovare la grandezza di m tale da avere la stessa prob di errore  del bloom filter. Ovviamente nel testo è vaga questa cosa. 

Quindi dal secondo paragrafo, dovrebbe essere m=ceil(2/f) hai ragione.  e cambierebbero anche un po i conti. Appena ho tempo li aggiorno. 

Grazie per la nota

**Comment by andreamad8** [comment]
Fuck I wrote it in italian... sorry

**Comment by Andrea-V** [comment]
Ahaha thanks to you! Please close this issue as soon as the solution is ok.
