### ISSUE TITLE
Ex04 prosal to modification

### ISSUE THREAD

**Issue by delleciliege** [andreamad8/Algo2Problems#16]
I updated the solution of ex4 with a modification in the proof of the first point.
The problems with the previous solution was (in my opinion):
- we didn't stress the fact that the random choice is on h and not on k,
- since k is not choose at random we must say the probability of error taken each possible k, and then we must say that the probability is 0 if k is in S,
- the probability given is the probability of error for an element which is not in S,
- the probability of error is the probability that B_s[h(k)] = 1, than it is the probability that
                \exists j\in S : h(k)=h(j) 
  and not the probability that
                \exists j\in S : h(k)=h(j)  but  j =\= k 
  as we say in the previous solution (look at the point b, here we use the probability exactly as I tell here!)
- I think collision is not the right term to express that an element j in S has the same hash function of 
      (i.e. h(k) = h(j)), since it is a collision only if also k is in S (and in that case we don't care of any other j).

I left the previous version in the tex file, you can restore it ore take the new version or merge, let me know what you think.

**Comment by andreamad8** [comment]
Okay, sound reasonable. We can also close the issue :)
