### ISSUE TITLE
Ex10: Some problem that I will fix

### ISSUE THREAD

**Issue by delleciliege** [andreamad8/Algo2Problems#4]
I think there are some problems with the solution of ex10.

In particular:
1. In the construction of T it's not clear that we use nj^2 and not nj (becomes clear in the last part of the solution);
2. In the calculation of the space occupied we can't use O(n) since it's required o(n).
3. There are some error in calculations (log(2n^2) is not < 2log(n), log(2n^2) = log(2) + log(n^2) = 1 + 2log(n));
4. We need to store also a and b for the first level of hash function (cost < log(2n) each)
5. Since each hash function h_(a,b) comes from a possibly different family we need to store also p (a,b,p for each bucket);
6. Since for hash function is needed also nj^2 maybe is better to explain how to obtain from what we have, without memorizing explicitly (I know it's trivial but it clarifies probably).

I think I already have the solutions to these problems, so please concentrate on the next problems, I wrote exactly for advertising that the correction is arriving today or tomorrow.

**Comment by andreamad8** [comment]
Perfect 👍

**Comment by delleciliege** [comment]
Done!
Please duble-check

**Comment by andreamad8** [comment]
I will have a look soon, sorry to be late

**Comment by delleciliege** [comment]
thank you

**Comment by andreamad8** [comment]
Yeah, I think mega okay
