### ISSUE TITLE
EX9

### ISSUE THREAD

**Issue by Aanok** [andreamad8/Algo2Problems#6]
I looked at the proof and I think it mostly checks out. My only issue is when you state E[X_i] < eps/e*||F||_1: when you're at level i you don't have F~ but rather an F~_i with n/2^i "buckets", each of which represents 2^i of the original elements. The above inequality holds, but only because the frequencies of the buckets are the sum of the frequencies of the original elements, which summed over the whole vector give again the 1-norm of F. This should be pointed out, imho.

**Comment by andreamad8** [comment]
Yah, I thought, instead, was for the same reason explained in class.  Because we keep 2log(n) disjoined interval, and the we apply a kind of "linearity". 
However, I do not fully understand what do u mean. Could u in case modify the solution.

**Comment by Aanok** [comment]
I mean that the CMS tables of levels above aren't built on the same vector as the base sequence, so the inequality should be E[X-i] < eps/e*||F_i||_1, but it happens that ||F_i||_1 = ||F||_1.
I'll make a note in the solution, then.

**Comment by andreamad8** [comment]
Ok, perfect

**Comment by Andrea-V** [comment]
Can someone explain better the consideration made right after the application of Markov's Inequality? It "feels" to me that there should be a summation somewhere. In particular I don't get the part where  ||F_i||_1 = ||F_j||_1 = || F ||_1. Are i and j different rows of the same sketch, or are different sketches? In particular, I think we should find a way to clarify the notation.

**Comment by Aanok** [comment]
They are different sketches. Each table has an F~_i thus also (in line of principle) an F_i.
You can see it as associating each new sketch to a reencoding of the original stream, where you have partitioned the alphabet in 2^i subsets of symbols and represented each of them with a single new symbol.
Say: ABCD, AB --> E, CD --> F; each time you witness A or B you count an occurrence of E, each time you witness C or D you count an occurrence of F.
Point is, the sum of all occurrences stays the same because that's the number of stream symbols you've witnessed, that is ||F_i|| = ||F|| for each i.
I left this bit out because it felt like gratuitous overcomplication.

EDIT - ah sorry, I see the issue. The i in X_i is the index of an interval in the dyadic partition and is not in principle linked to any particular depth in the CMS tree (in particular, X_i isn't necessarily at depth i). Aright, I'll see to it today.

EDIT2 - updated, take a look and close the issue if you're satisfied.

**Comment by Andrea-V** [comment]
Ok now I think that part is clear. The only thing I still i'm not so sure is how we're going to use the dyadic intervals (that is how we're going to build the "tree of dyadic intervals"). An example: let's say I have  a stream of N = 16 different items, this means I need to use log N = 4 CMSs, one for each i  in {0,1,2,3}. So the first CMS (i=0) will correspond to the interval [x+1, x+1], the second CMS (i=1) to [2x+1, 2x+2] and so on. So the elements will be partioned like in the picture:
![img_0597 1](https://cloud.githubusercontent.com/assets/9765364/20765884/7e576cda-b734-11e6-9350-75d665f6c2bd.JPG)
Then the sketch corresponding to (i=3) will count occurences of "A_3" and "B_3" (will count an "A_3" every time a number in {0,1,2,3,4,5,6,7} arrives, and a "B_3" when a {8,9,10,11,12,13,14,15} arrives.); the  (i=2) sketch will count A_2, B_2, C_2, D_2 and so on.
am I right? Then for each interval I just need to sum the corresponding dyadic intervals. (e.g. if I receive a query for (7, 13), then i can just sum up the occurences of "C_2", "G_1" and "7").
- Am I right? Is this the way we're using the intervals?
- It feels to me that the x parameters is used to identify which are the dyadic intervals a generic interval falls into, right? how can I do that?
PS: thanks for uploading the corrections/clarifications

**Comment by Aanok** [comment]
That is indeed the way we're using intervals.
For the purposes of the exercise, the dyadic partitioning comes from the Grace of God :p but it's actually pretty simple to compute: http://pastebin.com/3BGJ6tVY
("n" denotes set intersection, "c" denotes set inclusion, "::" is list concatenation)

**Comment by andreamad8** [comment]
@Andrea-V  your example looks very good, do u mind to put it in the EX9 solution ?
Also with an image no problem. Thanks a lot

**Comment by Andrea-V** [comment]
Sure! Done.
